### ISSUE TITLE
small except in transform content

### ISSUE THREAD

**Issue by Gehbt** [Simon-He95/transformToTailwindcss#20]
### Describe the bug

tailwindcssprop like `content-['_']`, IntelliSense explain it as `content: " "`
![image](https://github.com/Simon-He95/transformToTailwindcss/assets/74761884/24b6e370-7839-46ab-b53f-00f116f9be7b)
as for `content: "_"` we need use '\\_' : `content-['\_']`  
![image](https://github.com/Simon-He95/transformToTailwindcss/assets/74761884/3e443028-89a0-4180-be87-32dd18265937)

### Reproduction

none

### System Info

```shell
none
```

### Used Package Manager

npm

**Comment by Simon-He95** [comment]
Already compatible
